#include "P16F84.inc"
TEMP EQU 0XC
BSF STATUS,5 ; IR A LA PÁGINA1
CLRF TRISA
BSF TRISA,4
CLRF TRISB ;TODOS LOS BITS DEL PUERTO B SON SALIDA
BCF STATUS,5 ;IR A PÁGINA 0
CLRF PORTB ;INICIO DEL PORTB A CERO
MOVLW H'55'
MOVWF PORTB
INCF PORTA,1
CALL RETRASO
CICLO
INCF PORTA,1
CALL RETRASO
GOTO CICLO
RETRASO
MOVLW 0XA4 ;D'81' PARA 250 MICROSEGUNDOS D'53' es 3khz H'A5'1khz     ;1 CICLO
MOVWF TEMP    ;1 CICLO
LOOP
DECFSZ TEMP,1  ;1 CICLO / 2CICLOS CUANDO SALTA
GOTO LOOP       ;2 CICLOS POR EL SALTO
RETURN             ;2 CICLOS POR EL REGRESO
;CALCULANDO 500-4= 3(N) N=496/3=165.3 APROX 165 QUE ES A4
END