;DIVISIÓN 6/3 Y 7/3
DIVIDENDO EQU 0XC
DIVISOR EQU 0XD
COCIENTE EQU 0XE
MOVLW D'6'
MOVWF DIVIDENDO ;GUARA EL VALOR INMEDIATO 
MOVLW D'3'
MOVWF DIVISOR; GUARDA EL VALOR INMEDIATO
CLRF COCIENTE ;COCIENTE SE INICIA A 0
CICLO ;ETIQUETA DE INICIO DEL CICLO
INCF COCIENTE,F ;INCREMENTA EN 1 Y ALMACENA EL VALOR EN EL REGISTRO UTILIZADO
MOVF DIVISOR,W ;INDICA MOVER EL VALOR DEL REGISTRO DIVISOR A W
SUBWF DIVIDENDO,F ; DIDVIDENOD=DIVIDENDO-W(DIVISOR)
BTFSC STATUS,C ;BIT TEST FILE STATUS BIT ACARREO=0 SIGNO NEGATIVO
GOTO CICLO ;REGRESA AL CICLO
DECF COCIENTE,F ;DECREMENTE EN 1 EL REGISTRO COCIENTE
LOOP
GOTO LOOP ;FIN DEL PROGRAMA

